# Generated by Django 4.2 on 2023-04-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.CharField(blank=True, db_index=True, max_length=148, null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='post',
            name='create_at',
            field=models.DateField(auto_now=True, verbose_name='Create Datetime'),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(db_index=True, default='Anonymous', max_length=14, verbose_name='Name'),
        ),
    ]
